<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115132650 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversation (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, last_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8A8E26E9D17F50A6 ON conversation (uuid)');
        $this->addSql('CREATE INDEX IDX_8A8E26E9B03A8386 ON conversation (created_by_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E9896DBBDE ON conversation (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E9C76F1F52 ON conversation (deleted_by_id)');
        $this->addSql('CREATE TABLE participant (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, last_read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, participant_id INT NOT NULL, conversation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D79F6B11D17F50A6 ON participant (uuid)');
        $this->addSql('CREATE INDEX IDX_D79F6B11B03A8386 ON participant (created_by_id)');
        $this->addSql('CREATE INDEX IDX_D79F6B11896DBBDE ON participant (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_D79F6B11C76F1F52 ON participant (deleted_by_id)');
        $this->addSql('CREATE INDEX IDX_D79F6B119D1C3019 ON participant (participant_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_in_conversation ON participant (conversation_id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B11B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B11896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B11C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B119D1C3019 FOREIGN KEY (participant_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B119AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9B03A8386');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9896DBBDE');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9C76F1F52');
        $this->addSql('ALTER TABLE participant DROP CONSTRAINT FK_D79F6B11B03A8386');
        $this->addSql('ALTER TABLE participant DROP CONSTRAINT FK_D79F6B11896DBBDE');
        $this->addSql('ALTER TABLE participant DROP CONSTRAINT FK_D79F6B11C76F1F52');
        $this->addSql('ALTER TABLE participant DROP CONSTRAINT FK_D79F6B119D1C3019');
        $this->addSql('ALTER TABLE participant DROP CONSTRAINT FK_D79F6B119AC0396');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE participant');
    }
}
