<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115121513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_block (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, blocker_id INT NOT NULL, blocked_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_61D96C7AD17F50A6 ON user_block (uuid)');
        $this->addSql('CREATE INDEX IDX_61D96C7AB03A8386 ON user_block (created_by_id)');
        $this->addSql('CREATE INDEX IDX_61D96C7A896DBBDE ON user_block (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_61D96C7AC76F1F52 ON user_block (deleted_by_id)');
        $this->addSql('CREATE INDEX IDX_61D96C7A548D5975 ON user_block (blocker_id)');
        $this->addSql('CREATE INDEX IDX_61D96C7A21FF5136 ON user_block (blocked_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_block ON user_block (blocker_id, blocked_id)');
        $this->addSql('ALTER TABLE user_block ADD CONSTRAINT FK_61D96C7AB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_block ADD CONSTRAINT FK_61D96C7A896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_block ADD CONSTRAINT FK_61D96C7AC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_block ADD CONSTRAINT FK_61D96C7A548D5975 FOREIGN KEY (blocker_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_block ADD CONSTRAINT FK_61D96C7A21FF5136 FOREIGN KEY (blocked_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_block DROP CONSTRAINT FK_61D96C7AB03A8386');
        $this->addSql('ALTER TABLE user_block DROP CONSTRAINT FK_61D96C7A896DBBDE');
        $this->addSql('ALTER TABLE user_block DROP CONSTRAINT FK_61D96C7AC76F1F52');
        $this->addSql('ALTER TABLE user_block DROP CONSTRAINT FK_61D96C7A548D5975');
        $this->addSql('ALTER TABLE user_block DROP CONSTRAINT FK_61D96C7A21FF5136');
        $this->addSql('DROP TABLE user_block');
    }
}
