<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115144517 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media_asset (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, filename VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, media_pack_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1DB69EEDD17F50A6 ON media_asset (uuid)');
        $this->addSql('CREATE INDEX IDX_1DB69EEDB03A8386 ON media_asset (created_by_id)');
        $this->addSql('CREATE INDEX IDX_1DB69EED896DBBDE ON media_asset (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_1DB69EEDC76F1F52 ON media_asset (deleted_by_id)');
        $this->addSql('CREATE INDEX IDX_1DB69EED78CE345E ON media_asset (media_pack_id)');
        $this->addSql('CREATE TABLE media_pack (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, is_premium_only BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_549981F0D17F50A6 ON media_pack (uuid)');
        $this->addSql('CREATE INDEX IDX_549981F0B03A8386 ON media_pack (created_by_id)');
        $this->addSql('CREATE INDEX IDX_549981F0896DBBDE ON media_pack (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_549981F0C76F1F52 ON media_pack (deleted_by_id)');
        $this->addSql('ALTER TABLE media_asset ADD CONSTRAINT FK_1DB69EEDB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_asset ADD CONSTRAINT FK_1DB69EED896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_asset ADD CONSTRAINT FK_1DB69EEDC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_asset ADD CONSTRAINT FK_1DB69EED78CE345E FOREIGN KEY (media_pack_id) REFERENCES media_pack (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_pack ADD CONSTRAINT FK_549981F0B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_pack ADD CONSTRAINT FK_549981F0896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_pack ADD CONSTRAINT FK_549981F0C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media_asset DROP CONSTRAINT FK_1DB69EEDB03A8386');
        $this->addSql('ALTER TABLE media_asset DROP CONSTRAINT FK_1DB69EED896DBBDE');
        $this->addSql('ALTER TABLE media_asset DROP CONSTRAINT FK_1DB69EEDC76F1F52');
        $this->addSql('ALTER TABLE media_asset DROP CONSTRAINT FK_1DB69EED78CE345E');
        $this->addSql('ALTER TABLE media_pack DROP CONSTRAINT FK_549981F0B03A8386');
        $this->addSql('ALTER TABLE media_pack DROP CONSTRAINT FK_549981F0896DBBDE');
        $this->addSql('ALTER TABLE media_pack DROP CONSTRAINT FK_549981F0C76F1F52');
        $this->addSql('DROP TABLE media_asset');
        $this->addSql('DROP TABLE media_pack');
    }
}
