<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115120437 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE follow (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, follower_id INT NOT NULL, target_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_68344470D17F50A6 ON follow (uuid)');
        $this->addSql('CREATE INDEX IDX_68344470B03A8386 ON follow (created_by_id)');
        $this->addSql('CREATE INDEX IDX_68344470896DBBDE ON follow (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_68344470C76F1F52 ON follow (deleted_by_id)');
        $this->addSql('CREATE INDEX IDX_68344470AC24F853 ON follow (follower_id)');
        $this->addSql('CREATE INDEX IDX_68344470158E0B66 ON follow (target_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_follow ON follow (follower_id, target_id)');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470AC24F853 FOREIGN KEY (follower_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470158E0B66 FOREIGN KEY (target_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470B03A8386');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470896DBBDE');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470C76F1F52');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470AC24F853');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470158E0B66');
        $this->addSql('DROP TABLE follow');
    }
}
