<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115122842 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE moderation_vote (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, reason VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, post_id INT NOT NULL, reporter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9865976D17F50A6 ON moderation_vote (uuid)');
        $this->addSql('CREATE INDEX IDX_B9865976B03A8386 ON moderation_vote (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B9865976896DBBDE ON moderation_vote (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_B9865976C76F1F52 ON moderation_vote (deleted_by_id)');
        $this->addSql('CREATE INDEX IDX_B98659764B89032C ON moderation_vote (post_id)');
        $this->addSql('CREATE INDEX IDX_B9865976E1CFE6F5 ON moderation_vote (reporter_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_report_per_user ON moderation_vote (post_id, reporter_id)');
        $this->addSql('ALTER TABLE moderation_vote ADD CONSTRAINT FK_B9865976B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE moderation_vote ADD CONSTRAINT FK_B9865976896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE moderation_vote ADD CONSTRAINT FK_B9865976C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE moderation_vote ADD CONSTRAINT FK_B98659764B89032C FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE moderation_vote ADD CONSTRAINT FK_B9865976E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE moderation_vote DROP CONSTRAINT FK_B9865976B03A8386');
        $this->addSql('ALTER TABLE moderation_vote DROP CONSTRAINT FK_B9865976896DBBDE');
        $this->addSql('ALTER TABLE moderation_vote DROP CONSTRAINT FK_B9865976C76F1F52');
        $this->addSql('ALTER TABLE moderation_vote DROP CONSTRAINT FK_B98659764B89032C');
        $this->addSql('ALTER TABLE moderation_vote DROP CONSTRAINT FK_B9865976E1CFE6F5');
        $this->addSql('DROP TABLE moderation_vote');
    }
}
