<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115143107 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE badge (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, icon_name VARCHAR(255) NOT NULL, condition_rule VARCHAR(50) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FEF0481DD17F50A6 ON badge (uuid)');
        $this->addSql('CREATE INDEX IDX_FEF0481DB03A8386 ON badge (created_by_id)');
        $this->addSql('CREATE INDEX IDX_FEF0481D896DBBDE ON badge (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_FEF0481DC76F1F52 ON badge (deleted_by_id)');
        $this->addSql('CREATE TABLE notification (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, type VARCHAR(50) NOT NULL, message VARCHAR(255) NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, target_url VARCHAR(255) DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, receiver_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BF5476CAD17F50A6 ON notification (uuid)');
        $this->addSql('CREATE INDEX IDX_BF5476CAB03A8386 ON notification (created_by_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA896DBBDE ON notification (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAC76F1F52 ON notification (deleted_by_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CACD53EDB6 ON notification (receiver_id)');
        $this->addSql('CREATE TABLE user_badge (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, acquired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, owner_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1C32B345D17F50A6 ON user_badge (uuid)');
        $this->addSql('CREATE INDEX IDX_1C32B345B03A8386 ON user_badge (created_by_id)');
        $this->addSql('CREATE INDEX IDX_1C32B345896DBBDE ON user_badge (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_1C32B345C76F1F52 ON user_badge (deleted_by_id)');
        $this->addSql('CREATE INDEX IDX_1C32B3457E3C61F9 ON user_badge (owner_id)');
        $this->addSql('CREATE INDEX IDX_1C32B345F7A2C2FC ON user_badge (badge_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_badge_by_user ON user_badge (owner_id, badge_id)');
        $this->addSql('ALTER TABLE badge ADD CONSTRAINT FK_FEF0481DB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE badge ADD CONSTRAINT FK_FEF0481D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE badge ADD CONSTRAINT FK_FEF0481DC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CACD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B3457E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE badge DROP CONSTRAINT FK_FEF0481DB03A8386');
        $this->addSql('ALTER TABLE badge DROP CONSTRAINT FK_FEF0481D896DBBDE');
        $this->addSql('ALTER TABLE badge DROP CONSTRAINT FK_FEF0481DC76F1F52');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAB03A8386');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA896DBBDE');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAC76F1F52');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CACD53EDB6');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345B03A8386');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345896DBBDE');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345C76F1F52');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B3457E3C61F9');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345F7A2C2FC');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE user_badge');
    }
}
