<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115110525 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE interaction (created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, type VARCHAR(50) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, post_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_378DFDA7D17F50A6 ON interaction (uuid)');
        $this->addSql('CREATE INDEX IDX_378DFDA7B03A8386 ON interaction (created_by_id)');
        $this->addSql('CREATE INDEX IDX_378DFDA7896DBBDE ON interaction (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_378DFDA7C76F1F52 ON interaction (deleted_by_id)');
        $this->addSql('CREATE INDEX IDX_378DFDA74B89032C ON interaction (post_id)');
        $this->addSql('CREATE INDEX IDX_378DFDA7F675F31B ON interaction (author_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_interaction_per_user ON interaction (post_id, author_id, type)');
        $this->addSql('ALTER TABLE interaction ADD CONSTRAINT FK_378DFDA7B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interaction ADD CONSTRAINT FK_378DFDA7896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interaction ADD CONSTRAINT FK_378DFDA7C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interaction ADD CONSTRAINT FK_378DFDA74B89032C FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE interaction ADD CONSTRAINT FK_378DFDA7F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE interaction DROP CONSTRAINT FK_378DFDA7B03A8386');
        $this->addSql('ALTER TABLE interaction DROP CONSTRAINT FK_378DFDA7896DBBDE');
        $this->addSql('ALTER TABLE interaction DROP CONSTRAINT FK_378DFDA7C76F1F52');
        $this->addSql('ALTER TABLE interaction DROP CONSTRAINT FK_378DFDA74B89032C');
        $this->addSql('ALTER TABLE interaction DROP CONSTRAINT FK_378DFDA7F675F31B');
        $this->addSql('DROP TABLE interaction');
    }
}
